#include <stdio.h>
#include <stdlib.h>
#include "../lib/hexaNow.h"
#include "../lib/message.h"
#define  SIZE_ASCII 		255
#define  VALOR_INICIAL 		0
#define  QT_POS_REPRE_HEXA 	4


void runInitResource (HEXANOW *hexanowRefer);
static void initEquivalences  (DATA_RESOURCE *dataResourceRefer);
static void chargeASCIIValues (DATA_RESOURCE *dataResourceRefer);

void runInitResource (HEXANOW *hexanowRefer) {
   initSysColor ();
   setColorYellowText ();
   printf (__MESSAGE_INIT1__);
   DATA_RESOURCE dataResource 	      = 	*(DATA_RESOURCE*)malloc(sizeof(DATA_RESOURCE));
   dataResource.equivalenceList	      =	  (EQUIVALENCE*)malloc(SIZE_ASCII * sizeof(EQUIVALENCE));
   dataResource.lenEquivalence        =   *(int*)malloc(sizeof(int));
   initEquivalences  (&dataResource);   
   chargeASCIIValues (&dataResource);
   printf (__MESSAGE_INIT2__);
   printf (__MESSAGE_INIT3__);
   hexanowRefer->dataASC_ON           = 1;
   hexanowRefer->dataResourceObject   = dataResource;
   system("PAUSE");
   setColorWhiteText();
}

static void initEquivalences (DATA_RESOURCE *dataResourceRefer) {
	//Carregando os cursores
   EQUIVALENCE* equivalenceCursor;
   EQUIVALENCE  equivalenceObj;
   unsigned int LEN_LOOP				  =	SIZE_ASCII;
   unsigned int CONTROL_LOOP			=	VALOR_INICIAL;
   equivalenceCursor 					    =	dataResourceRefer->equivalenceList;

   for (; CONTROL_LOOP < LEN_LOOP; CONTROL_LOOP++) {
   		equivalenceObj						= *(EQUIVALENCE*)malloc(sizeof(equivalenceObj));
   		equivalenceObj.caracter 			= *(char*)malloc(sizeof(char));
   		equivalenceObj.hexaEquivalence		=  (char*)calloc(QT_POS_REPRE_HEXA, sizeof(char));
   		*(equivalenceCursor + CONTROL_LOOP)	=	equivalenceObj;	
   }

   equivalenceCursor = NULL;
   free (equivalenceCursor);
}

static void chargeASCIIValues (DATA_RESOURCE *dataResourceRefer) {

	EQUIVALENCE* equivalenceCursor		=	dataResourceRefer->equivalenceList;
    
    EQUIVALENCE  *referObj0				 =	(equivalenceCursor + 0);
	referObj0->caracter     			   =   ' ';   
    referObj0->hexaEquivalence		 = 	"00h";
	EQUIVALENCE  *referObj1				   =	(equivalenceCursor + 1);
	referObj1->caracter     			   =   ' ';    
    referObj1->hexaEquivalence		 = 	"01h";
	EQUIVALENCE  *referObj2				   =	(equivalenceCursor + 2);
	referObj2->caracter     			   =   ' ';    
    referObj2->hexaEquivalence		 = 	"02h";
    EQUIVALENCE  *referObj3				 =	(equivalenceCursor + 3);
	referObj3->caracter     			   =   ' ';    
    referObj3->hexaEquivalence		 = 	"03h";
    EQUIVALENCE  *referObj4				 =	(equivalenceCursor + 4);
	referObj4->caracter     			   =   ' ';    
    referObj4->hexaEquivalence		 = 	"04h";
    EQUIVALENCE  *referObj5				 =	(equivalenceCursor + 5);
	referObj5->caracter     			   =   ' ';    
    referObj5->hexaEquivalence		 = 	"05h";
    EQUIVALENCE  *referObj6				 =	(equivalenceCursor + 6);
	referObj6->caracter     			   =   ' ';    
    referObj6->hexaEquivalence		 = 	"06h";
    EQUIVALENCE  *referObj7				 =	(equivalenceCursor + 7);
	referObj7->caracter     			   =   ' ';    
    referObj7->hexaEquivalence		 = 	"07h";
    EQUIVALENCE  *referObj8				 =	(equivalenceCursor + 8);
	referObj8->caracter     			   =   ' ';    
    referObj8->hexaEquivalence		 = 	"08h";
    EQUIVALENCE  *referObj9				 =	(equivalenceCursor + 9);
	referObj9->caracter     			   =   ' ';    
    referObj9->hexaEquivalence		 = 	"09h";
    EQUIVALENCE  *referObj10			 =	(equivalenceCursor + 10);
	referObj10->caracter     			   =   ' ';    
    referObj10->hexaEquivalence		 = 	"0Ah";
    EQUIVALENCE  *referObj11			 =	(equivalenceCursor + 11);
	referObj11->caracter     			   =   ' ';    
    referObj11->hexaEquivalence		 = 	"0Bh";
    EQUIVALENCE  *referObj12			 =	(equivalenceCursor + 12);
	referObj12->caracter     			   =   ' ';    
    referObj12->hexaEquivalence		 = 	"0Ch";
    EQUIVALENCE  *referObj13			 =	(equivalenceCursor + 13);
	referObj13->caracter     			   =   ' ';    
    referObj13->hexaEquivalence		 = 	"0Dh";
    EQUIVALENCE  *referObj14			 =	(equivalenceCursor + 14);
	referObj14->caracter     			   =   ' ';    
    referObj14->hexaEquivalence		 = 	"0Eh";
    EQUIVALENCE  *referObj15			 =	(equivalenceCursor + 15);
	referObj15->caracter     			   =   ' ';    
    referObj15->hexaEquivalence		 = 	"0Fh";
    EQUIVALENCE  *referObj16       =  (equivalenceCursor + 16);
    referObj16->caracter             =   ' ';    
    referObj16->hexaEquivalence    =  "10h";
    EQUIVALENCE  *referObj17       =  (equivalenceCursor + 17);
    referObj17->caracter             =   ' ';    
    referObj17->hexaEquivalence    =  "11h";
    EQUIVALENCE  *referObj18       =  (equivalenceCursor + 18);
    referObj18->caracter             =   ' ';    
    referObj18->hexaEquivalence    =  "12h";
    EQUIVALENCE  *referObj19       =  (equivalenceCursor + 19);
    referObj19->caracter             =   ' ';    
    referObj19->hexaEquivalence    =  "13h";
    EQUIVALENCE  *referObj20       =  (equivalenceCursor + 20);
    referObj20->caracter             =   ' ';    
    referObj20->hexaEquivalence    =  "14h";
    EQUIVALENCE  *referObj21      =  (equivalenceCursor + 21);
    referObj21->caracter             =   ' ';    
    referObj21->hexaEquivalence    =  "15h";
    EQUIVALENCE  *referObj22       =  (equivalenceCursor + 22);
    referObj22->caracter             =   ' ';    
    referObj22->hexaEquivalence    =  "16h";
    EQUIVALENCE  *referObj23       =  (equivalenceCursor + 23);
    referObj23->caracter             =   ' ';    
    referObj23->hexaEquivalence    =  "17h";
    EQUIVALENCE  *referObj24       =  (equivalenceCursor + 24);
    referObj24->caracter             =   ' ';    
    referObj24->hexaEquivalence    =  "18h";
    EQUIVALENCE  *referObj25      =  (equivalenceCursor + 25);
    referObj25->caracter             =   ' ';    
    referObj25->hexaEquivalence    =  "19h";
    EQUIVALENCE  *referObj26       =  (equivalenceCursor + 26);
    referObj26->caracter             =   ' ';    
    referObj26->hexaEquivalence    =  "1Ah";
    EQUIVALENCE  *referObj27       =  (equivalenceCursor + 27);
    referObj27->caracter             =   ' ';    
    referObj27->hexaEquivalence    =  "1Bh";
    EQUIVALENCE  *referObj28       =  (equivalenceCursor + 28);
    referObj28->caracter             =   ' ';    
    referObj28->hexaEquivalence    =  "1Ch";
    EQUIVALENCE  *referObj29       =  (equivalenceCursor + 29);
    referObj29->caracter             =   ' ';    
    referObj29->hexaEquivalence    =  "1Dh";
    EQUIVALENCE  *referObj30       =  (equivalenceCursor + 30);
    referObj30->caracter             =   ' ';    
    referObj30->hexaEquivalence    =  "1Eh";
    EQUIVALENCE  *referObj31       =  (equivalenceCursor + 31);
    referObj31->caracter             =   ' ';    
    referObj31->hexaEquivalence    =  "1Fh";
    EQUIVALENCE  *referObj32       =  (equivalenceCursor + 32);
    referObj32->caracter             =   ' ';    
    referObj32->hexaEquivalence    =  "20h";
    EQUIVALENCE  *referObj33       =  (equivalenceCursor + 33);
    referObj33->caracter             =   '!';    
    referObj33->hexaEquivalence    =  "21h";
    EQUIVALENCE  *referObj34       =  (equivalenceCursor + 34);
    referObj34->caracter             =   '"';    
    referObj34->hexaEquivalence    =  "22h";
    EQUIVALENCE  *referObj35       =  (equivalenceCursor + 35);
    referObj35->caracter             =   '#';    
    referObj35->hexaEquivalence    =  "23h";
    EQUIVALENCE  *referObj36       =  (equivalenceCursor + 36);
    referObj36->caracter             =   '$';    
    referObj36->hexaEquivalence    =  "24h";
    EQUIVALENCE  *referObj37       =  (equivalenceCursor + 37);
    referObj37->caracter             =   '%';    
    referObj37->hexaEquivalence    =  "25h";
    EQUIVALENCE  *referObj38       =  (equivalenceCursor + 38);
    referObj38->caracter             =   '&';    
    referObj38->hexaEquivalence    =  "26h";
    EQUIVALENCE  *referObj39       =  (equivalenceCursor + 39);
    referObj39->caracter             =   '\'';    
    referObj39->hexaEquivalence    =  "27h";
    EQUIVALENCE  *referObj40       =  (equivalenceCursor + 40);
    referObj40->caracter             =   '(';    
    referObj40->hexaEquivalence    =  "28h";
    EQUIVALENCE  *referObj41       =  (equivalenceCursor + 41);
    referObj41->caracter             =   ')';    
    referObj41->hexaEquivalence    =  "29h";
    EQUIVALENCE  *referObj42       =  (equivalenceCursor + 42);
    referObj42->caracter             =   '*';    
    referObj42->hexaEquivalence    =  "2Ah";
    EQUIVALENCE  *referObj43       =  (equivalenceCursor + 43);
    referObj43->caracter             =   '+';    
    referObj43->hexaEquivalence    =  "2Bh";
    EQUIVALENCE  *referObj44       =  (equivalenceCursor + 44);
    referObj44->caracter             =   ',';    
    referObj44->hexaEquivalence    =  "2Ch";
    EQUIVALENCE  *referObj45       =  (equivalenceCursor + 45);
    referObj45->caracter             =   '-';    
    referObj45->hexaEquivalence    =  "2Dh";
    EQUIVALENCE  *referObj46       =  (equivalenceCursor + 46);
    referObj46->caracter             =   '.';    
    referObj46->hexaEquivalence    =  "2Eh";
    EQUIVALENCE  *referObj47       =  (equivalenceCursor + 47);
    referObj47->caracter             =   '/';    
    referObj47->hexaEquivalence    =  "2Fh";
    EQUIVALENCE  *referObj48       =  (equivalenceCursor + 48);
    referObj48->caracter             =   '0';    
    referObj48->hexaEquivalence    =  "30h";
    EQUIVALENCE  *referObj49       =  (equivalenceCursor + 49);
    referObj49->caracter           =   '1';    
    referObj49->hexaEquivalence    =  "31h";
    EQUIVALENCE  *referObj50       =  (equivalenceCursor + 50);
    referObj50->caracter           =   '2';    
    referObj50->hexaEquivalence    =  "32h";
    EQUIVALENCE  *referObj51       =  (equivalenceCursor + 51);
    referObj51->caracter           =   '3';    
    referObj51->hexaEquivalence    =  "33h";
    EQUIVALENCE  *referObj52       =  (equivalenceCursor + 52);
    referObj52->caracter           =   '4';    
    referObj52->hexaEquivalence    =  "34h";
    EQUIVALENCE  *referObj53       =  (equivalenceCursor + 53);
    referObj53->caracter           =   '5';    
    referObj53->hexaEquivalence    =  "35h";
    EQUIVALENCE  *referObj54       =  (equivalenceCursor + 54);
    referObj54->caracter           =   '6';    
    referObj54->hexaEquivalence    =  "36h";
    EQUIVALENCE  *referObj55       =  (equivalenceCursor + 55);
    referObj55->caracter           =   '7';    
    referObj55->hexaEquivalence    =  "37h";
    EQUIVALENCE  *referObj56       =  (equivalenceCursor + 56);
    referObj56->caracter           =   '8';    
    referObj56->hexaEquivalence    =  "38h";
    EQUIVALENCE  *referObj57       =  (equivalenceCursor + 57);
    referObj57->caracter           =   '9';    
    referObj57->hexaEquivalence    =  "39h";
    EQUIVALENCE  *referObj58       =  (equivalenceCursor + 58);
    referObj58->caracter           =   ':';    
    referObj58->hexaEquivalence    =  "3Ah";
    EQUIVALENCE  *referObj59       =  (equivalenceCursor + 59);
    referObj59->caracter           =   ';';    
    referObj59->hexaEquivalence    =  "3Bh";
    EQUIVALENCE  *referObj60       =  (equivalenceCursor + 60);
    referObj60->caracter           =   '<';    
    referObj60->hexaEquivalence    =  "3Ch";
    EQUIVALENCE  *referObj61       =  (equivalenceCursor + 61);
    referObj61->caracter           =   '=';    
    referObj61->hexaEquivalence    =  "3Dh";
    EQUIVALENCE  *referObj62       =  (equivalenceCursor + 62);
    referObj62->caracter           =   '>';    
    referObj62->hexaEquivalence    =  "3Eh";
    EQUIVALENCE  *referObj63       =  (equivalenceCursor + 63);
    referObj63->caracter           =   '?';    
    referObj63->hexaEquivalence    =  "3Fh";
    EQUIVALENCE  *referObj64       =  (equivalenceCursor + 64);
    referObj64->caracter           =   '@';    
    referObj64->hexaEquivalence    =  "40h";
    EQUIVALENCE  *referObj65       =  (equivalenceCursor + 65);
    referObj65->caracter           =   'A';    
    referObj65->hexaEquivalence    =  "41h";
    EQUIVALENCE  *referObj66       =  (equivalenceCursor + 66);
    referObj66->caracter           =   'B';    
    referObj66->hexaEquivalence    =  "42h";
    EQUIVALENCE  *referObj67       =  (equivalenceCursor + 67);
    referObj67->caracter           =   'C';    
    referObj67->hexaEquivalence    =  "43h";
    EQUIVALENCE  *referObj68       =  (equivalenceCursor + 68);
    referObj68->caracter           =   'D';    
    referObj68->hexaEquivalence    =  "44h";
    EQUIVALENCE  *referObj69       =  (equivalenceCursor + 69);
    referObj69->caracter           =   'E';    
    referObj69->hexaEquivalence    =  "45h";
    EQUIVALENCE  *referObj70       =  (equivalenceCursor + 70);
    referObj70->caracter           =   'F';    
    referObj70->hexaEquivalence    =  "46h";
    EQUIVALENCE  *referObj71       =  (equivalenceCursor + 71);
    referObj71->caracter           =   'G';    
    referObj71->hexaEquivalence    =  "47h";
    EQUIVALENCE  *referObj72       =  (equivalenceCursor + 72);
    referObj72->caracter           =   'H';    
    referObj72->hexaEquivalence    =  "48h";
    EQUIVALENCE  *referObj73       =  (equivalenceCursor + 73);
    referObj73->caracter           =   'I';    
    referObj73->hexaEquivalence    =  "49h";
    EQUIVALENCE  *referObj74       =  (equivalenceCursor + 74);
    referObj74->caracter           =   'J';    
    referObj74->hexaEquivalence    =  "4Ah";
    EQUIVALENCE  *referObj75       =  (equivalenceCursor + 75);
    referObj75->caracter           =   'K';    
    referObj75->hexaEquivalence    =  "4Bh";
    EQUIVALENCE  *referObj76       =  (equivalenceCursor + 76);
    referObj76->caracter           =   'L';    
    referObj76->hexaEquivalence    =  "4Ch";
    EQUIVALENCE  *referObj77      =  (equivalenceCursor + 77);
    referObj77->caracter           =   'M';    
    referObj77->hexaEquivalence    =  "4Dh";
    EQUIVALENCE  *referObj78       =  (equivalenceCursor + 78);
    referObj78->caracter           =   'N';    
    referObj78->hexaEquivalence    =  "4Eh";
    EQUIVALENCE  *referObj79       =  (equivalenceCursor + 79);
    referObj79->caracter           =   'O';    
    referObj79->hexaEquivalence    =  "4Fh";
    EQUIVALENCE  *referObj80       =  (equivalenceCursor + 80);
    referObj80->caracter           =   'P';    
    referObj80->hexaEquivalence    =  "50h";
    EQUIVALENCE  *referObj81       =  (equivalenceCursor + 81);
    referObj81->caracter           =   'Q';    
    referObj81->hexaEquivalence    =  "51h";
    EQUIVALENCE  *referObj82       =  (equivalenceCursor + 82);
    referObj82->caracter           =   'R';    
    referObj82->hexaEquivalence    =  "52h";
    EQUIVALENCE  *referObj83       =  (equivalenceCursor + 83);
    referObj83->caracter           =   'S';    
    referObj83->hexaEquivalence    =  "53h";
    EQUIVALENCE  *referObj84       =  (equivalenceCursor + 84);
    referObj84->caracter           =   'T';    
    referObj84->hexaEquivalence    =  "54h";
    EQUIVALENCE  *referObj85       =  (equivalenceCursor + 85);
    referObj85->caracter           =   'U';    
    referObj85->hexaEquivalence    =  "55h";
    EQUIVALENCE  *referObj86       =  (equivalenceCursor + 86);
    referObj86->caracter           =   'V';    
    referObj86->hexaEquivalence    =  "56h";
    EQUIVALENCE  *referObj87       =  (equivalenceCursor + 87);
    referObj87->caracter           =   'W';    
    referObj87->hexaEquivalence    =  "57h";
    EQUIVALENCE  *referObj88       =  (equivalenceCursor + 88);
    referObj88->caracter           =   'X';    
    referObj88->hexaEquivalence    =  "58h";
    EQUIVALENCE  *referObj89       =  (equivalenceCursor + 89);
    referObj89->caracter           =   'Y';    
    referObj89->hexaEquivalence    =  "59h";
    EQUIVALENCE  *referObj90       =  (equivalenceCursor + 90);
    referObj90->caracter           =   'Z';    
    referObj90->hexaEquivalence    =  "5Ah";
    EQUIVALENCE  *referObj91      =  (equivalenceCursor + 91);
    referObj91->caracter           =   '[';    
    referObj91->hexaEquivalence    =  "5Bh";
    EQUIVALENCE  *referObj92       =  (equivalenceCursor + 92);
    referObj92->caracter           =   '\\';    
    referObj92->hexaEquivalence    =  "5Ch";
    EQUIVALENCE  *referObj93       =  (equivalenceCursor + 93);
    referObj93->caracter           =   ']';    
    referObj93->hexaEquivalence    =  "5Dh";
    EQUIVALENCE  *referObj94      =  (equivalenceCursor + 94);
    referObj94->caracter           =   '^';    
    referObj94->hexaEquivalence    =  "5Eh";
    EQUIVALENCE  *referObj95       =  (equivalenceCursor + 95);
    referObj95->caracter           =   '_';    
    referObj95->hexaEquivalence    =  "5Fh";
    EQUIVALENCE  *referObj96      =  (equivalenceCursor + 96);
    referObj96->caracter           =   '`';    
    referObj96->hexaEquivalence    =  "60h";
    EQUIVALENCE  *referObj97       =  (equivalenceCursor + 97);
    referObj97->caracter           =   'a';    
    referObj97->hexaEquivalence    =  "61h";
    EQUIVALENCE  *referObj98      =  (equivalenceCursor + 98);
    referObj98->caracter           =   'b';    
    referObj98->hexaEquivalence    =  "62h";
    EQUIVALENCE  *referObj99       =  (equivalenceCursor + 99);
    referObj99->caracter           =   'c';    
    referObj99->hexaEquivalence    =  "63h";
    EQUIVALENCE  *referObj100       =  (equivalenceCursor + 100);
    referObj100->caracter           =   'd';    
    referObj100->hexaEquivalence    =  "64h";

	dataResourceRefer->lenEquivalence = 100;
    equivalenceCursor				  =	NULL;
    free (equivalenceCursor);
}
